flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
- location:
    git: https://github.com/jgm/pandoc-types.git
    commit: 973394685aad945ccd92a86bf76e5c644e72e127
- location:
    git: https://github.com/jgm/texmath.git
    commit: 31273683a376e97848028e4619f28ab8c03c88af
extra-deps:
- doctemplates-0.1.0.2
- skylighting-0.1.0.1
resolver: lts-7.14
